name: deploy

on:
  push: 
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # actions/checkout@v4

      - name: "Install ssh keys"
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} > ~/.ssh/known_hosts

      - name: "Connect to vm, pull latest changes & reload app"
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
          cd hng12-stage2-fastapi-book-project/
          git pull origin main
          sudo docker build -t fastapi-app .
          sudo docker stop fastapi-app || true
          sudo docker rm fastapi-app || true
          sudo docker run -d --name fastapi-app -p 8000:8000 fastapi-app

          # Copy the nginx.conf file to the VM
          sudo cp ./nginx.conf /etc/nginx/nginx.conf

          # Test the Nginx configuration
          sudo nginx -t

          # Reload Nginx to apply the new configuration
          sudo systemctl reload nginx
          EOF

      - name: cleanup
        run: rm -rf ~/.ssh
